import type { ModerationReport, ModerationReportDetail } from "@/types/admin"

export const MOCK_MODERATION_REPORTS: ModerationReport[] = [
  {
    id: "TRV-8902",
    date: "2026-04-18T14:30:00",
    author: { name: "Julian M.", avatarUrl: "https://i.pravatar.cc/40?u=trv8902" },
    category: "spam",
    reportCount: 12,
    status: "pending",
  },
  {
    id: "TRV-8914",
    date: "2026-04-18T15:12:00",
    author: { name: "Elena Rose", avatarUrl: "https://i.pravatar.cc/40?u=trv8914" },
    category: "inappropriate",
    reportCount: 4,
    status: "pending",
  },
  {
    id: "TRV-9011",
    date: "2026-04-18T16:45:00",
    author: { name: "David Chen", avatarUrl: "https://i.pravatar.cc/40?u=trv9011" },
    category: "hate_speech",
    reportCount: 1,
    status: "pending",
  },
  {
    id: "TRV-9122",
    date: "2026-04-18T17:01:00",
    author: { name: "Sarah King", avatarUrl: "https://i.pravatar.cc/40?u=trv9122" },
    category: "spam",
    reportCount: 28,
    status: "pending",
  },
  {
    id: "TRV-9205",
    date: "2026-04-19T09:15:00",
    author: { name: "Marco Bianchi", avatarUrl: "https://i.pravatar.cc/40?u=trv9205" },
    category: "fraud",
    reportCount: 7,
    status: "pending",
  },
  {
    id: "TRV-9318",
    date: "2026-04-19T10:40:00",
    author: { name: "Aiko Tanaka", avatarUrl: "https://i.pravatar.cc/40?u=trv9318" },
    category: "misinformation",
    reportCount: 3,
    status: "pending",
  },
  {
    id: "TRV-9401",
    date: "2026-04-20T08:22:00",
    author: { name: "Lars Eriksson", avatarUrl: "https://i.pravatar.cc/40?u=trv9401" },
    category: "fraud",
    reportCount: 61,
    status: "pending",
  },
  {
    id: "TRV-9488",
    date: "2026-04-20T11:05:00",
    author: { name: "Priya Nair", avatarUrl: "https://i.pravatar.cc/40?u=trv9488" },
    category: "inappropriate",
    reportCount: 9,
    status: "pending",
  },
  {
    id: "TRV-9530",
    date: "2026-04-21T13:30:00",
    author: { name: "Carlos Ruiz", avatarUrl: "https://i.pravatar.cc/40?u=trv9530" },
    category: "misinformation",
    reportCount: 2,
    status: "pending",
  },
  {
    id: "TRV-9601",
    date: "2026-04-21T16:10:00",
    author: { name: "Fatima Al-Hassan", avatarUrl: "https://i.pravatar.cc/40?u=trv9601" },
    category: "hate_speech",
    reportCount: 15,
    status: "pending",
  },
  {
    id: "TRV-8701",
    date: "2026-04-10T09:00:00",
    author: { name: "Tom Nguyen", avatarUrl: "https://i.pravatar.cc/40?u=trv8701" },
    category: "spam",
    reportCount: 45,
    status: "resolved",
  },
  {
    id: "TRV-8750",
    date: "2026-04-12T14:20:00",
    author: { name: "Amara Diallo", avatarUrl: "https://i.pravatar.cc/40?u=trv8750" },
    category: "fraud",
    reportCount: 18,
    status: "resolved",
  },
  {
    id: "TRV-8820",
    date: "2026-04-14T11:55:00",
    author: { name: "Wei Zhang", avatarUrl: "https://i.pravatar.cc/40?u=trv8820" },
    category: "inappropriate",
    reportCount: 6,
    status: "resolved",
  },
  {
    id: "TRV-8855",
    date: "2026-04-15T10:30:00",
    author: { name: "Sophie Martin", avatarUrl: "https://i.pravatar.cc/40?u=trv8855" },
    category: "hate_speech",
    reportCount: 22,
    status: "resolved",
  },
  {
    id: "TRV-8890",
    date: "2026-04-16T16:45:00",
    author: { name: "Ravi Kapoor", avatarUrl: "https://i.pravatar.cc/40?u=trv8890" },
    category: "misinformation",
    reportCount: 5,
    status: "resolved",
  },
]

export const MOCK_MODERATION_DETAILS: Record<string, ModerationReportDetail> = {
  "TRV-8902": {
    ...MOCK_MODERATION_REPORTS[0],
    content: "This hotel is a total scam! They took my deposit and cancelled last minute. When I called, the manager was incredibly offensive and told me to get out. Avoid at all costs!",
    authorSince: "March 2023",
    aiViolations: ["SCAM", "OFFENSIVE"],
    evidence: [
      { reporterCount: 8, violationType: "Spam" },
      { reporterCount: 4, violationType: "Harassment" },
    ],
  },
  "TRV-8914": {
    ...MOCK_MODERATION_REPORTS[1],
    content: "The photos on this listing are completely fake. Nothing like the actual place. I feel totally misled and this is unacceptable behavior from a host.",
    authorSince: "January 2024",
    aiViolations: ["INAPPROPRIATE"],
    evidence: [
      { reporterCount: 3, violationType: "Inappropriate Content" },
      { reporterCount: 1, violationType: "Misleading" },
    ],
  },
  "TRV-9011": {
    ...MOCK_MODERATION_REPORTS[2],
    content: "People from this country are all thieves and liars. Do NOT stay here if you value your safety or your money.",
    authorSince: "August 2022",
    aiViolations: ["HATE_SPEECH", "OFFENSIVE"],
    evidence: [
      { reporterCount: 1, violationType: "Hate Speech" },
    ],
  },
  "TRV-9122": {
    ...MOCK_MODERATION_REPORTS[3],
    content: "BUY NOW! Cheapest hotel in the city guaranteed! Click my link for special discount! Limited time offer! Best price EVER! Don't miss out!",
    authorSince: "November 2023",
    aiViolations: ["SPAM"],
    evidence: [
      { reporterCount: 15, violationType: "Spam" },
      { reporterCount: 13, violationType: "Advertisement" },
    ],
  },
  "TRV-9205": {
    ...MOCK_MODERATION_REPORTS[4],
    content: "I paid for the premium room but was given a closet-sized room instead. When I complained they demanded cash to 'upgrade' me back to what I already paid for. This is fraud.",
    authorSince: "May 2023",
    aiViolations: ["FRAUD"],
    evidence: [
      { reporterCount: 5, violationType: "Fraud" },
      { reporterCount: 2, violationType: "Extortion" },
    ],
  },
  "TRV-9318": {
    ...MOCK_MODERATION_REPORTS[5],
    content: "The owner told me this hotel won the UNESCO World Heritage Award for hospitality. That is completely false and I verified with UNESCO directly. Dangerous misinformation.",
    authorSince: "September 2023",
    aiViolations: ["MISINFORMATION"],
    evidence: [
      { reporterCount: 2, violationType: "Misinformation" },
      { reporterCount: 1, violationType: "False Claims" },
    ],
  },
  "TRV-9401": {
    ...MOCK_MODERATION_REPORTS[6],
    content: "Wire $500 to this account and get a free 5-star room! I have done it 3 times and it always works. Trust me, this is 100% legitimate and risk-free.",
    authorSince: "February 2022",
    aiViolations: ["FRAUD", "SCAM"],
    evidence: [
      { reporterCount: 44, violationType: "Fraud" },
      { reporterCount: 17, violationType: "Scam" },
    ],
  },
  "TRV-9488": {
    ...MOCK_MODERATION_REPORTS[7],
    content: "The staff left explicit material in the room and made very uncomfortable comments to my partner. This place is unsafe and completely inappropriate for families.",
    authorSince: "July 2023",
    aiViolations: ["INAPPROPRIATE"],
    evidence: [
      { reporterCount: 6, violationType: "Inappropriate Content" },
      { reporterCount: 3, violationType: "Harassment" },
    ],
  },
  "TRV-9530": {
    ...MOCK_MODERATION_REPORTS[8],
    content: "The owner claims this building is 200 years old and on the national historic registry. I checked — the building was constructed in 2015. Pure fabrication to charge more.",
    authorSince: "October 2023",
    aiViolations: ["MISINFORMATION"],
    evidence: [
      { reporterCount: 2, violationType: "False Claims" },
    ],
  },
  "TRV-9601": {
    ...MOCK_MODERATION_REPORTS[9],
    content: "People like the owners of this place should be deported. Their kind doesn't belong in the hospitality industry. I will never support businesses run by people like them.",
    authorSince: "April 2022",
    aiViolations: ["HATE_SPEECH", "OFFENSIVE"],
    evidence: [
      { reporterCount: 10, violationType: "Hate Speech" },
      { reporterCount: 5, violationType: "Discrimination" },
    ],
  },
  "TRV-8701": {
    ...MOCK_MODERATION_REPORTS[10],
    content: "BEST DEAL CLICK HERE NOW AMAZING PRICE FREE UPGRADE LIMITED OFFER ACT NOW DON'T MISS OUT SPECIAL DISCOUNT TODAY ONLY.",
    authorSince: "June 2021",
    aiViolations: ["SPAM"],
    evidence: [
      { reporterCount: 30, violationType: "Spam" },
      { reporterCount: 15, violationType: "Advertisement" },
    ],
  },
  "TRV-8750": {
    ...MOCK_MODERATION_REPORTS[11],
    content: "They charged my card three times after checkout and when I disputed the charges they threatened legal action if I left a negative review. Classic fraud scheme.",
    authorSince: "December 2021",
    aiViolations: ["FRAUD"],
    evidence: [
      { reporterCount: 12, violationType: "Fraud" },
      { reporterCount: 6, violationType: "Threats" },
    ],
  },
  "TRV-8820": {
    ...MOCK_MODERATION_REPORTS[12],
    content: "The host sent unsolicited and inappropriate messages throughout my stay. The content was offensive and I felt unsafe. This behavior is completely unacceptable.",
    authorSince: "March 2022",
    aiViolations: ["INAPPROPRIATE"],
    evidence: [
      { reporterCount: 4, violationType: "Inappropriate Content" },
      { reporterCount: 2, violationType: "Harassment" },
    ],
  },
  "TRV-8855": {
    ...MOCK_MODERATION_REPORTS[13],
    content: "The receptionist made racist remarks about my nationality when I checked in and laughed when I complained to the manager. This is completely unacceptable behavior.",
    authorSince: "August 2021",
    aiViolations: ["HATE_SPEECH", "DISCRIMINATION"],
    evidence: [
      { reporterCount: 18, violationType: "Hate Speech" },
      { reporterCount: 4, violationType: "Discrimination" },
    ],
  },
  "TRV-8890": {
    ...MOCK_MODERATION_REPORTS[14],
    content: "The listing claims this hotel was featured in Forbes Travel Guide 2025 Platinum Edition. I contacted Forbes and they have no record of this hotel in any of their publications.",
    authorSince: "January 2022",
    aiViolations: ["MISINFORMATION"],
    evidence: [
      { reporterCount: 4, violationType: "False Claims" },
      { reporterCount: 1, violationType: "Impersonation" },
    ],
  },
}
